name: Fire Everything
favicon: null
layout_spectrum: 0.47816125210374594
typography_spectrum: 0.28428
title: 'Don''t know how to design? Me neither! '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5e4d8'
    - '#372723'
    - '#edba81'
    - '#070000'
    - '#8d613c'
  brandStrength: 0.0625
  lightness: 0.3037689521443099
  saturation: 0.8194932825863361
  rhythmicContrast: 0.5985136113595217
purpose: []
